# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceCGPT.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.resposta = QtWidgets.QLabel(self.centralwidget)
        self.resposta.setAlignment(QtCore.Qt.AlignCenter)
        self.resposta.setObjectName("resposta")
        self.gridLayout.addWidget(self.resposta, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btnPesquisar = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesquisar.setObjectName("btnPesquisar")
        self.gridLayout.addWidget(self.btnPesquisar, 3, 0, 1, 1)
        self.entradaUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.entradaUsuario.setObjectName("entradaUsuario")
        self.gridLayout.addWidget(self.entradaUsuario, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.saidaText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.saidaText.setObjectName("saidaText")
        self.gridLayout_2.addWidget(self.saidaText, 1, 0, 1, 3)
        self.btnLimparTexto = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimparTexto.setObjectName("btnLimparTexto")
        self.gridLayout_2.addWidget(self.btnLimparTexto, 2, 0, 1, 1)
        self.btnPlayAudio = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlayAudio.setObjectName("btnPlayAudio")
        self.gridLayout_2.addWidget(self.btnPlayAudio, 2, 1, 1, 1)
        self.btnPararAudio = QtWidgets.QPushButton(self.centralwidget)
        self.btnPararAudio.setObjectName("btnPararAudio")
        self.gridLayout_2.addWidget(self.btnPararAudio, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pesquisa IA"))
        self.resposta.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Digite sua pesquisa:"))
        self.btnPesquisar.setText(_translate("MainWindow", "Pesquisar"))
        self.btnLimparTexto.setText(_translate("MainWindow", "Limpar"))
        self.btnPlayAudio.setText(_translate("MainWindow", "Play Audio"))
        self.btnPararAudio.setText(_translate("MainWindow", "Parar"))
